# Generated by Django 4.0.5 on 2022-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anime_studio_alter_anime_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='demographic',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='eps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='eps_avg_duration_in_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='rated_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='theme',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='anime',
            name='year',
            field=models.FloatField(default=0),
        ),
    ]
