# Generated by Django 4.0.5 on 2022-06-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_anime_demographic_anime_eps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='eps',
            field=models.FloatField(default=0),
        ),
    ]
