# Generated by Django 4.0.5 on 2022-06-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_anime_eps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='eps_avg_duration_in_min',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='year',
        ),
    ]
